### ISSUE TITLE
bash completion does not work in macos

### ISSUE THREAD

**Issue by ziranjameshe** [lincheney/fzf-tab-completion#86]
```
fzf-tab-completion/bash/fzf-bash-completion.sh: line 555: unexpected EOF while looking for matching `"'
fzf-tab-completion/bash/fzf-bash-completion.sh: line 560: syntax error: unexpected end of file
```

**Comment by lincheney** [comment]
Hello
What version of bash do you have installed

**Comment by ziranjameshe** [comment]
Hey, tried both bash `3.2.57` and `4.4.20`. Problem exist on both.

**Comment by ArtBIT** [comment]
Same issue here. Using 
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin23)

**Comment by lincheney** [comment]
I can reproduce this issue on bash 3 only and not bash 4.
For bash 3, can you please upgrade to a more recent version of bash

**Comment by ziranjameshe** [comment]
Thanks for the quick turnaround.

I am pretty sure I have tried installing the bash 4+, but seeing the same issue.

Can we not just fix the problem?

**Comment by ziranjameshe** [comment]
Hey, just tried bash 5. I can source in the script now. Do you not get a `tac: command not found error`?

I think `tac` only available on linux.

**Comment by ziranjameshe** [comment]
> Hey, just tried bash 5. I can source in the script now. Do you not get a `tac: command not found error`?
> 
> I think `tac` only available on linux.

Actually, I can resolve this by installing `brew install coreutils`. But there is some strange behaviour with sed now.

I am seeing `sed: First RE may not be empty` with a `cd <TAB>` showing all the available bash command

**Comment by dhcabinian** [comment]
+1 to the `sed: First RE may not be empty` on macOS with `GNU bash, version 5.2.21(1)-release (x86_64-apple-darwin23.0.0)` and showing a listing of all possible bash commands.

**Comment by lincheney** [comment]
if you can pinpoint which `sed` in the script is failing, that would be helpful
If you do `set -x` and then try it, it should print out the commands it runs, and then you may be able to find which `sed` command is problematic

**Comment by dhcabinian** [comment]
`set -x` gives the following traceback: ```+++ printf '%s\n' ' '
+++ buffer=
+++ IFS=
+++ read -r line
+++ case "$line" in
+++ ((  count < 0  ))
+++ ((  count > 0  ))
+++ printf '%s\n' git
+++ buffer=
+++ IFS=
+++ read -r line
+++ printf '%s\n' ''
sed: first RE may not be empty
++ [[ 0 -gt 1 ]]
+++ printf %s
++ COMP_LINE=
++ COMP_POINT=0
++ readarray -t COMP_WORDS
+++ printf '%s\n'
+++ ggrep '[^[:space:]]'
++ [[ 0 = 0 ]]
++ COMP_WORDS+=('')
++ COMP_CWORD=1
++ ((  COMP_CWORD--  )``` pointing at 

_fzf_bash_completion_parse_line which fails at the sed pipe here: 

```
        | _fzf_bash_completion_flatten_subshells \
        | tr \\n \\0 \
        | "$_fzf_bash_completion_sed" -r "$(cat <<'EOF'

```

https://github.com/lincheney/fzf-tab-completion/blob/f6f83c88eca0fc07f7820dd8bb6c7ea75ef478c5/bash/fzf-bash-completion.sh#L126C1-L128C56

**Comment by lincheney** [comment]
i think this may be due to the null bytes, mac sed probably can't handle it, i 'll see if i can change it to something else

**Comment by lincheney** [comment]
I have pushed this https://github.com/lincheney/fzf-tab-completion/commit/9616591b74c72c0f716b214c659b2c3c91964e75, hoping it may fix some of the issues.

**Comment by ziranjameshe** [comment]
> I have pushed this [9616591](https://github.com/lincheney/fzf-tab-completion/commit/9616591b74c72c0f716b214c659b2c3c91964e75), hoping it may fix some of the issues.

Thanks for looking. This doesn't seem to fix the issue.

The behaviour now is `TAB` won't return any match

**Comment by lincheney** [comment]
> I have pushed this [9616591](https://github.com/lincheney/fzf-tab-completion/commit/9616591b74c72c0f716b214c659b2c3c91964e75), hoping it may fix some of the issues.

I've had to revert this as it was causing other [issues](https://github.com/lincheney/fzf-tab-completion/issues/90).
Can you please try install gnu sed instead.
